name: Secure Policy Agent
description: Centralized policy enforcement

inputs:
  pr_number:
    description: Pull request number
    required: true

runs:
  using: composite
  steps:
    - name: Checkout application repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        pip install semgrep pyyaml PyGithub

    - name: Merge security policies
      shell: bash
      run: python "$GITHUB_ACTION_PATH/scripts/policy_merger.py"

    - name: Extract policy
      shell: bash
      run: python "$GITHUB_ACTION_PATH/scripts/policy_extractor.py"

    - name: Compile Semgrep rules
      shell: bash
      run: python "$GITHUB_ACTION_PATH/scripts/policy_mapper.py"

    - name: Run Semgrep (PR diff only)
      shell: bash
      continue-on-error: true
      run: |
        semgrep scan \
          --config security-policies/semgrep.yaml \
          --baseline-commit origin/${{ github.base_ref }} \
          --json > semgrep-results.json

    - name: Comment on PR
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: python "$GITHUB_ACTION_PATH/scripts/pr_commenter.py"

    - name: Fail job if Semgrep found violations
      shell: bash
      run: |
        jq -e '.results | length == 0' semgrep-results.json


    # - name: Run Semgrep (PR diff only)
    #   uses: returntocorp/semgrep-action@v1
    #   continue-on-error: true
    #   with:
    #     config: security-policies/semgrep.yaml
    #     baseline-ref: origin/${{ github.base_ref }}
    #     json: true
    #     output: semgrep-results.json

    # - name: Comment on PR
    #   shell: bash
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #     PR_NUMBER: ${{ github.event.pull_request.number }}
    #   run: python "$GITHUB_ACTION_PATH/scripts/pr_commenter.py"

    # - name: Fail job if Semgrep found violations
    #   shell: bash
    #   run: |
    #     jq -e '.results | length == 0' semgrep-results.json

