name: Secure Policy Agent
description: Centralized policy enforcement

inputs:
  pr_number:
    description: Pull request number
    required: true

runs:
  using: composite
  steps:
    - name: Checkout application repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        echo "::group::Install dependencies"
        pip install semgrep pyyaml PyGithub
        echo "::endgroup::"

    - name: Merge security policies
      shell: bash
      run: |
        echo "::group::Merge security policies"
        python "$GITHUB_ACTION_PATH/scripts/policy_merger.py"
        cat "$GITHUB_WORKSPACE/merged-copilot-policy.md"
        echo "::endgroup::"

    - name: Extract policy
      shell: bash
      run: |
        echo "::group::Extract policy"
        python "$GITHUB_ACTION_PATH/scripts/policy_extractor.py"
        echo "::endgroup::"

    - name: Compile Semgrep rules
      shell: bash
      run: |
        echo "::group::Compile Semgrep rules"
        python "$GITHUB_ACTION_PATH/scripts/policy_mapper.py"
        echo "::endgroup::"

    - name: Run Semgrep (PR diff only)
      shell: bash
      continue-on-error: true
      run: |
        echo "::group::Run Semgrep (PR diff only)"
        semgrep scan \
          --config security-policies/semgrep.yaml \
          --baseline-commit origin/${{ github.base_ref }} \
          --json > semgrep-results.json
        echo "::endgroup::"

    - name: Comment on PR
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ inputs.pr_number }}
      run: |
        echo "::group::Comment on PR"
        python "$GITHUB_ACTION_PATH/scripts/pr_commenter.py"
        echo "::endgroup::"

    - name: Fail job if Semgrep found violations
      shell: bash
      run: |
        echo "::group::Fail job if Semgrep found violations"
        jq -e '.results | length == 0' semgrep-results.json
        echo "::endgroup::"
